// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuKTnpRDZ7BWL4TbJ3-CPnTzXneMXrszM',
    appId: '1:541298258980:web:0bb6c118820748a46194b1',
    messagingSenderId: '541298258980',
    projectId: 'mock-mart',
    authDomain: 'mock-mart.firebaseapp.com',
    storageBucket: 'mock-mart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf6EqKPo85RuESPfxTM9JHETVEB2K6T4k',
    appId: '1:541298258980:android:504d924604f02c066194b1',
    messagingSenderId: '541298258980',
    projectId: 'mock-mart',
    storageBucket: 'mock-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkJkstuBBf-UvncnrUpieUzjxaJi_huDI',
    appId: '1:541298258980:ios:91d40df3e62812866194b1',
    messagingSenderId: '541298258980',
    projectId: 'mock-mart',
    storageBucket: 'mock-mart.firebasestorage.app',
    iosBundleId: 'com.example.mockMart',
  );
}
